version: "3"

services:
  cachedb:
    image: redis:alpine
    container_name: movies-cache
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6399:6379"
  database:
    image: postgres:latest
    container_name: movies-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lib
    ports:
      - 35432:5432
    volumes:
      - movie_data:/var/lib/postgresql/data
  server:
    build: ./services
    container_name: movies-server
    command: sh -c "dockerize -wait tcp://database:5432 -wait tcp://cachedb:6379 -timeout 300s -wait-retry-interval 10s npm run start:prod"
    depends_on:
      - database
      - cachedb
    environment:
      APPHOST: localhost
      APPPORT: 7080
      DBHOST: database
      DBPORT: 5432
      DBUSERNAME: postgres
      DBPASSWORD: 123
      DBDATABASE: lib
      DBSCHEMA: public
      DBRATETABLE: movies
      REDIS_URL: tcp://cachedb:6379
    ports:
      - 7080:7080
      - 81:81
  app:
    build: ./apps
    container_name: movies-app
    depends_on:
      - server
    links:
      - server
    ports:
      - 8080:80

volumes:
  movie_data:
    driver: local