export enum EMovieTypes {
  'Action' = 'action',
  'Adult' = 'adult',
  'Adventure' = 'adventure',
  'Animation' = 'animation',
  'Biography' = 'biography',
  'Comedy' = 'comedy',
  'Crime' = 'crime',
  'Documentary' = 'documentary',
  'Drama' = 'drama',
  'Family' = 'family',
  'Fantasy' = 'fantasy',
  'FilmNoir' = 'filmnoir',
  'History' = 'history',
  'Horror' = 'horror',
  'Music' = 'music',
  'Musical' = 'musical',
  'Mystery' = 'mystery',
  'News' = 'news',
  'Romance' = 'romance',
  'SciFi' = 'scifi',
  'Sport' = 'sport',
  'Thriller' = 'thriller',
  'War' = 'war',
  'Western' = 'western',
}

export enum ESocketEvent {
  'CREATEMOVIE' = 'createmovie',
  'UPDATEMOVIE' = 'updatemovie',
  'DELETEMOVIE' = 'deletemovie',
}
